# Generated by Django 5.1.4 on 2025-01-10 15:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Image related to the clue.', max_length=255, null=True, upload_to=core.models.clue_image_path),
        ),
    ]
