# Generated by Django 5.1.4 on 2025-01-10 19:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_pgvector_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='image_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3, help_text='LLM embedding of the reference image', null=True),
        ),
    ]
