# Generated by Django 5.1.4 on 2025-01-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_clue_image_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehunt',
            name='completion_message',
            field=models.TextField(default='Congratulations! You have completed the treasure hunt.', help_text='Message displayed when the user completes the hunt'),
        ),
    ]
